export default {
    BOOK_LIST: 'BOOK_LIST',
    BOOK_INFO: 'BOOK_INFO',
    SHOW_BOOK_EDIT: 'SHOW_BOOK_EDIT',
    SHOW_BOOK_ADD: 'SHOW_BOOK_ADD',
    
    USER_LIST: 'USER_LIST',
    USER_INFO: 'USER_INFO',
    SHOW_USER_EDIT: 'SHOW_USER_EDIT',
    SHOW_USER_ADD: 'SHOW_USER_ADD'
};